### PR TITLE
Improve chat interface

### LINKED ISSUE #2: Improve rendering function
It's pretty clear we need to improve the rendering page.

### LINKED ISSUE #3: Chat info wrong
image
Please double-check check sotopia paper to see how we deal with information asymmetry there. If I role-play agent 1, I should not be able to see agent 2's secret

### PR DESCRIPTION
**Pull request by bugsz**
Close #3 
Plan to close #2

### CODE REVIEW

**Comment by bugsz** [comment]
Here is an extremely simple demo for editable environment, in which agent goals and scenarios are changable. But there are some logical issues that needs to address.

**Comment by XuhuiZhou** [comment]
> Here is an extremely simple demo for editable environment, in which agent goals and scenarios are changable. But there are some logical issues that needs to address.

This is issue #4? Please move things to corresponding issues and address things in the corresponding branch name. 
`feature/better_rendering` should address #2

**Comment by bugsz** [comment]
I see. Actually this branch is mostly addressing #4 and addressing #3 only requires a few line (the first commit)
Maybe I just create a new branch that addresses #4 and #3 together?

**Comment by XuhuiZhou** [comment]
Sounds good to me!

**Pull request closed without merging**
