### PR TITLE
improve episode rendering page

### PR DESCRIPTION
**Pull request by bugsz**
In episode display page, now use the same rendering function with chat interface. 
User can also navigate the episodes by codename

### CODE REVIEW

**Comment by XuhuiZhou** [comment]
qq, what's this WS; GD stuff?
image

**Review by XuhuiZhou — CHANGES_REQUESTED** [review]
* Function-wise: have a button that would allow people to insert their own database. Also include a few existing options for people to select from, including AI-liedar.

* Aesthetics-wise: Any chance we can polish the interface a bit more? 
Here's one example:
http://128.2.218.53:8501/?pk=01J6GKFSV54CAZ43ETZ4D153NT

I also invited you to the repo so you can check the code there

**Comment by bugsz** [comment]
> qq, what's this WS; GD stuff? 

These are newly-designed scenarios and agents : )

> Any chance we can polish the interface a bit more?

Make some changes to make it looks better

> have a button that would allow people to insert their own database

Do you have any idea how to re-initialize redis database when we have already import all the related `redis-om` object? Find it hard to do so.

**Comment by ProKil** [comment]
Is there a preview version?

**Comment by XuhuiZhou** [comment]
@bugsz Thanks!! 
Here are a few comments after discussing with @ProKil, we think 
* Role-play mode [just show bare information, like the agent view, and it has no access to other agents' goal]
* Omniscient view
* editable view

**Comment by ProKil** [comment]
@bugsz it generally looks great! Could you move the context to the left side bar and leave the main space only for the chat interface?

**Comment by bugsz** [comment]
Sorry for a late update! 
@ProKil I move the context to the sidebar in chat mode, but I am not sure whether we need to do it on display mode as well as there are less information to show

@XuhuiZhou Seems like we need to write a new page for role-play mode as some information have to be removed and user have to choose which agent to be. Let me check what could be a better way to implement that

**Comment by bugsz** [comment]
@XuhuiZhou @ProKil Here is the update for role-play mode. Still a few things:
1. Any suggestion to the title for each mode? (Currently `Simple Chat` and `Omniscient Chat & Editable Scenario`)
2. Now I have a json file for quickly adding scenarios and agents. Do we need this?

**Review by XuhuiZhou — APPROVED** [review]

**Pull request merged**
